---
# A list of events to generate, in order
- type: ProcessStart
  path: '/usr/bin/uname'
  arguments: -a
  name: 'Fetch uname'

- type: CreateFile
  path: ./tmp/test.txt
  file_type: txt
  name: 'Create ./tmp/test.txt'

- type: ModifyFile
  path: ./tmp/test.txt
  name: 'Modify ./tmp/test.txt'

- type: DeleteFile
  path: ./tmp/test.txt
  name: 'Delete ./tmp/test.txt'

- type: NetworkRequest
  host: www.redcanary.com
  port: 80
  name: 'Say HELO to red canary on port 80'

